services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Robots-Delices-App-MVC
    ports:
      - 15050:80
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=database
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
  db:
    image: mysql
    container_name: Robots-Delices-DB-MVC
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Robots-Délices-DB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: Robots-Delices-phpMyAdmin-MVC
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db
volumes:
  db_data: